// admin/src/views/login/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useMutation } from '@vue/apollo-composable'
import gql from 'graphql-tag';
import { FetchResult } from '@apollo/client/core';
import { useRouter } from 'vue-router'

const username = ref('')

const password = ref('')

const router = useRouter()

const { mutate: loginResult } = useMutation(gql`
  mutation login($username: String, $password: String!) {
    login(loginInput: { email: $username, password: $password }) {
      email
      username
      token
    }
  }
`, () => ({
  variables: {
    username: username.value,
    password: password.value
  }
})) 

const handlelogin = async () => {
  const result: FetchResult<any, Record<string, any>, Record<string, any>> | null = await loginResult()
  if (result?.data) {
    localStorage.setItem('token', result.data.login.token)
    router.push('/')
  }
}

</script>

<template>
  <div class="login">
    <div class="login-control">
      登录界面
    </div>
    <div class="login-control">
      <el-input v-model="username" placeholder="请输入用户名或邮箱" />
    </div>
    <div class="login-control">
      <el-input type="password" show-password v-model="password" placeholder="请输入密码" />
    </div>
    <div class="login-control login-btn">
      <el-button type="primary" @click="handlelogin">登录</el-button>
    </div>
  </div>
</template>

<style scoped>
.login {
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}

.login-control {
  min-width: 300px;
  max-width: 600px;
  margin-bottom: 2rem;
}

.login-btn {
  min-width: 300px;
  max-width: 600px;
}

.login-btn button {
  width: 100%;
}
</style>

// unbalance/src/pages/login/index.tsx
import React, { ChangeEvent, useState } from "react";
import { useMutation, gql } from "@apollo/client";
import "./style.scss";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../context/authContext";

const LOGIN_TODO = gql`
  mutation LOGIN_TODO($username: String, $password: String!) {
    login(loginInput: { email: $username, password: $password }) {
      email
      username
      token
    }
  }
`;


const Login = () => {
  const auth = useAuth();
  const [username, setUsername] = useState(
    sessionStorage.getItem("username") || ""
  );
  const [password, setpassword] = useState(
    sessionStorage.getItem("password") || ""
  );

  const history = useNavigate()

  const [loginTodo] = useMutation(LOGIN_TODO);

  const handleChangeUsername = (event: ChangeEvent<HTMLInputElement>) => {
    sessionStorage.setItem("username", event.target.value);
    setUsername(event.target.value);
  };

  const handleChangePassword = (event: ChangeEvent<HTMLInputElement>) => {
    sessionStorage.setItem("password", event.target.value);
    setpassword(event.target.value);
  };

  const handleLogin = async () => {
    const result = await loginTodo({ variables: { username, password } });
    console.log(result.data)
    if (result.data) {
      auth.signin(result.data.login.username, () => {
        localStorage.setItem('token', result.data.login.token)
        sessionStorage.clear();
        history("/", { 
          replace: true,
          state: {
            username: result.data.login.username
          }
        })
      })
      
    }
  };

  return (
    <div className="w-full h-full relative">
      <div className="login-bg">
        <div className="login-drop-shadow">
          <div className="login-glass"></div>
          <div className="flex login-container">
            <div className="flex flex-col login-form">
              <header className="font-bold text-lg text-center">
                欢迎来到聊天室
              </header>
              <label htmlFor="username">账户名</label>
              <input
                id="username"
                type="text"
                value={username}
                onChange={(e) => handleChangeUsername(e)}
              />
              <label htmlFor="password">密码</label>
              <input
                id="password"
                type="password"
                value={password}
                onChange={(e) => handleChangePassword(e)}
              />
              <button className="login-button" onClick={handleLogin}>
                登录
              </button>
            </div>
            <div className="flex justify-center items-center login-aside">
              <div className="login-label">一个普通的聊天室</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
